version: "3"
services:
  phpmyadmin:
     image: phpmyadmin/phpmyadmin
     ports :
      - "8090:80"
     environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root
     links:
      - database:db

  database:
    image: mysql
    ports:
     - "3306:3306"
    volumes:
     - ./Database:/var/lib/mysql 
    environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=mydb