app:
  name: anuglar2-spring-jwt

jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: api/auth/login
      refresh: api/auth/refresh

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  h2:
    console:
      enabled: true
      path: /database
  datasource:
    url: jdbc:h2:file:./database/db
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


