INSERT INTO USER (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, ENABLED, LASTPASSWORDRESETDATE) VALUES (1, 'admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin', 'admin', 'admin@admin.com', 1, PARSEDATETIME('01-01-2016', 'dd-MM-yyyy'));
INSERT INTO USER (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, ENABLED, LASTPASSWORDRESETDATE) VALUES (2, 'user', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user', 'user', 'enabled@user.com', 1, PARSEDATETIME('01-01-2016','dd-MM-yyyy'));

INSERT INTO AUTHORITY (ID, NAME) VALUES (1, 'ROLE_USER');
INSERT INTO AUTHORITY (ID, NAME) VALUES (2, 'ROLE_ADMIN');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (1, 1);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (1, 2);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (2, 1);

INSERT INTO TODOITEM (ID, NAME, DESCRIPTION, USER_USERNAME) VALUES (1, 'TODOITEM1', 'DESCRIPTION', 'admin');
INSERT INTO TODOITEM (ID, NAME, DESCRIPTION, USER_USERNAME) VALUES (2, 'TODOITEM2', 'DESCRIPTION', 'admin');
INSERT INTO TODOITEM (ID, NAME, DESCRIPTION, USER_USERNAME) VALUES (3, 'TODOITEM3', 'DESCRIPTION', 'admin');
INSERT INTO TODOITEM (ID, NAME, DESCRIPTION, USER_USERNAME) VALUES (4, 'TODOITEM4', 'DESCRIPTION', 'admin');